### ISSUE TITLE
메인 페이지 구현

### ISSUE THREAD

**Issue by 2-hs2** [23-2-Media-Project/front#14]
## Description
메인 페이지 구현
## Todo
- [x] 3D 로고 적용 및 애니메이션 추가
- [x] 이달의 전시회 섹션 구현
- [x] 전시회 예시 데이터 생성 
- [x] 추천/인기/최신 전시회 섹션 구현
## Etc
X

**Comment by 2-hs2** [comment]
[위아래 무한 움직임 애니메이션 참고]
https://posting-apollo.tistory.com/55

**Comment by 2-hs2** [comment]
추후에 전시회 목록 클릭시 해당 전시회 페이지로 이동 구현 필요
