### ISSUE TITLE
전시회 작성 페이지 구현 - 기본 정보 입력 1,2

### ISSUE THREAD

**Issue by 2-hs2** [23-2-Media-Project/front#18]
## Description
전시회 작성 페이지 구현  (기본 정보 입력 1,2)
## Todo
- [x] 하단에 ProgressBar, 이전, 다음 버튼 구현

기본 정보 입력 1
- [x] Title : 기본 정보 입력
- [x] 전시회 제목, 분야 카테고리, 주제 카테고리, 썸네일 등록
- [x] 분야 카테고리 - 최소 1개, 최대 2개 선택 가능
- [x] 주제 카테고리 - 최소 1개, 최대 3개 선택 가능

기본 정보 입력 2
- [x] 각 카테고리 클릭 시 event 구현(background color / font color 변경)
- [x] 필수 입력 조건(분야, 주제 최소 1개 / 썸네일, 제목 모두 기재) 충족 시 다음 버튼 enable

## Etc
기타사항
- 마이페이지에서 글 작성 버튼을 통해 전시회 작성 페이지로 이동
