### ISSUE TITLE
이달의 전시회 페이지 - 첫 화면 배경 구현

### ISSUE THREAD

**Issue by 2-hs2** [23-2-Media-Project/front#19]
## Description
이달의 전시회 페이지에 배경으로 linear 그라디언트와 스크롤 하면 커지는 원형 애니메이션 구현.
## Todo
- [x] linear 그라디언트 배경 적용
- [x] 스크롤시 커지는 원형 애니메이션 구현
- [x] 스크롤 완료시 가운데 radial 그라디언트 생성
- [x] 이달의 전시회 내용 및 추천 전시회 구현
## Etc
해당 이슈 이후 계속해서 이달의 전시회 페이지 구현 필요

**Comment by 2-hs2** [comment]
[애니메이션 참고]
https://cocococo.tistory.com/entry/React-Framer-Motion3-%EC%8A%A4%ED%81%AC%EB%A1%A4useScroll-%EB%B0%8F-%EB%A1%9C%EA%B3%A0SVG%ED%8C%8C%EC%9D%BC-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-%ED%9A%A8%EA%B3%BC-%EC%A0%81%EC%9A%A9

**Comment by 2-hs2** [comment]
[scroll fade in 애니메이션 참고]
https://github.com/jus0k/scroll-hooks
