### ISSUE TITLE
전시회 작성 페이지 구현 - 작품 정보 입력 1,2

### ISSUE THREAD

**Issue by doyn511** [23-2-Media-Project/front#26]
## Description
전시회 작성 페이지 구현 (작품 정보 입력 1,2)
## Todo
- [x] 작품 정보 입력 Title
- [x] 1개의 작품 당 작품제목, 작품 첨부, 작품 설명 필요 (작품 첨부 필수)
- [x] 섹션 추가하기 구현
- [x] progress bar 생성(이전, 다음)
- [x] 게시한 작품 삭제 가능 (x버튼)
- [ ] 작품 별 순서 변경 가능

## Etc
기타사항 
X
