### ISSUE TITLE
전시회 작성 페이지 구현 - 상품 정보 입력

### ISSUE THREAD

**Issue by doyn511** [23-2-Media-Project/front#32]
## Description
상품 정보 입력 페이지 구현
## Todo
- [ ] 상품 이름, 상품 이미지, 상품 가격, 실물 여부 입력
- [ ] 섹션 추가 가능
- [ ] 이전, 다음으로 이동 가능

## Etc
기타사항
추후에 다음 게시글 등록 다음 라우팅 등록
