### ISSUE TITLE
전시회 상세 페이지 UI 구현

### ISSUE THREAD

**Issue by doyn511** [23-2-Media-Project/front#35]
## Description
전시회 상세 페이지 구현
## Todo
- [x] 기본정보: 제목, 작성자, 작성 날짜, 분야/주제
- [x] 작품 별 : 제목, 내용, 사진
- [x] 기타: 좋아요, 공유, 신고 아이콘
- [x] 관련 상품 : 상품 이름, 좋아요, 상품 사진, 가격, 실물/비실물 여부
## Etc
기타사항
전시회 작성 페이지와 라우팅 필요
