### ISSUE TITLE
데이터 추가 및 전시회 상세 페이지 연결

### ISSUE THREAD

**Issue by 2-hs2** [23-2-Media-Project/front#43]
## Description
데이터 추가 및 전시회 상세 페이지 연결
## Todo
- [x] 메인 페이지 데이터 추가
- [x] 전시회 목록 페이지 데이터 추가
- [x] 이달의 전시회 페이지 데이터 추가
- [x] 마이 페이지 데이터 추가
- [x] 구매 페이지 데이터 추가
- [x] 전시회 상세 페이지 데이터 추가
- [x] 전시회 상세 페이지 연결
## Etc
X
